server:
    port: 18081

spring:
    application:
        name: hello
    profiles:
        include: think-cloud
think:
    cloud:
        instance:
            instance-id: ${spring.application.name}
            service-id: ${spring.application.name}
            port: ${server.port}
            host: localhost
